export const SET_PRODUCT_TO_CALCULATOR = "SET_PRODUCT_TO_CALCULATOR";

export const CLOSE_CALCULATOR = "CLOSE_CALCULATOR";

export const ADD_FOOD_TO_CARTLIST = "ADD_FOOD_TO_CARTLIST";

export const DELETE_FOOD_FROM_CARTLIST = "DELETE_FOOD_FROM_CARTLIST";