export const SET_PRODUCT_TO_CALCULATOR = "SET_PRODUCT_TO_CALCULATOR";

export const CLOSE_CALCULATOR = "CLOSE_CALCULATOR";

export const ADD_FOOD_TO_CARTLIST = "ADD_FOOD_TO_CARTLIST";

export const DELETE_FOOD_FROM_CARTLIST = "DELETE_FOOD_FROM_CARTLIST";

export const UPDATE_TOTAL_COUNTER = "UPDATE_TOTAL_COUNTER";

export const CLEAN_SALES_WINDOW = "CLEAN_SALES_WINDOW";

export const CLOSE_ALERT = "CLOSE_ALERT";

export const OPEN_ALERT = "OPEN_ALERT";

export const HIDE_ALERT = "HIDE_ALERT";