export const SET_PRODUCT_TO_CALCULATOR = "SET_PRODUCT_TO_CALCULATOR";

export const CLOSE_CALCULATOR = "CLOSE_CALCULATOR";

export const ADD_FOOD_TO_CARTLIST = "ADD_FOOD_TO_CARTLIST";

export const SUBSTRACT_FOOD_TO_CARTLIST = "SUBSTRACT_FOOD_TO_CARTLIST";

export const UPDATE_TOTAL_COUNTER = "UPDATE_TOTAL_COUNTER";

export const CLEAN_SALES_WINDOW = "CLEAN_SALES_WINDOW";

export const CLOSE_ALERT = "CLOSE_ALERT";

export const OPEN_ALERT = "OPEN_ALERT";

export const HIDE_ALERT = "HIDE_ALERT";

export const SET_ACTUAL_FOOD_LIST = "SET_ACTUAL_FOOD_LIST";

export const SET_PRODUCT_CATEGORIES = "SET_PRODUCT_CATEGORIES";